import requests


def get_data(row, location):
    s = requests.Session()

    headers = {
        'authority': 'prd-west.webapi.nationalcar.com',
        'accept': 'application/json, text/plain, */*',
        'accept-language': 'en-US,en;q=0.9',
        'brand': 'NATIONAL',
        'channel': 'WEB',
        'domain_country_of_residence': 'US',
        'locale': 'en_US',
        'origin': 'https://www.nationalcar.com',
        'referer': 'https://www.nationalcar.com/',
        'sec-ch-ua': '".Not/A)Brand";v="99", "Google Chrome";v="103", "Chromium";v="103"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-site',
        'sofresh': 'SOCLEAN',
        'tab_id': '1659457757279_1',
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36',
    }

    json_data = {
        'pickup_location_id': location['id'],
        'show_cash_in_club_number': False,
        'iata_number': None,
        'return_location': {
            'filter_tags': [],
            'airport_code': location['airport_code'],
            'airline_details': [],
            'level_of_service_wayfindings': [],
            'additional_data': {
                'update_timestamp': location['additional_data']['update_timestamp'],
                'java_time_zone': 'America/New_York',
                'formatted_city_state_zip': location['additional_data']['formatted_city_state_zip'],
                'bookable': True,
                'is24HourLocation': location['additional_data']['is24HourLocation'],
                'co_located_station_id': location['station_id'],
                'group_branch_number': location['additional_data']['group_branch_number'],
                'co_located_brand': 'ALAMO',
                'enable_drive_alliance': False,
                'booking_url': 'https://www.nationalcar.com',
                'formatted_phone': location['additional_data']['formatted_phone'],
                'attributes_with_type': [
                    {
                        'type': 'BRAND',
                        'code': '',
                        'name': 'NATIONAL',
                    },
                    {
                        'type': 'BUSINESS_TYPE',
                        'code': '',
                        'name': 'ONE_WAYS',
                    },
                    {
                        'type': 'METHOD_OF_DELIVERY',
                        'code': 'CH',
                        'name': 'CHOICE',
                    },
                    {
                        'type': 'METHOD_OF_DELIVERY',
                        'code': 'CN',
                        'name': 'COUNTER',
                    },
                    {
                        'type': 'METHOD_OF_DELIVERY',
                        'code': 'EA',
                        'name': 'EMERALD_AISLE',
                    },
                    {
                        'type': 'METHOD_OF_DELIVERY',
                        'code': 'ER',
                        'name': 'EMERALD_RESERVE',
                    },
                    {
                        'type': 'METHOD_OF_DELIVERY',
                        'code': 'ES',
                        'name': 'EXECUTIVE_SELECTION',
                    },
                    {
                        'type': 'METHOD_OF_DELIVERY',
                        'code': 'FB',
                        'name': 'FBO_DELIVERY',
                    },
                    {
                        'type': 'METHOD_OF_DELIVERY',
                        'code': 'GR',
                        'name': 'RESERVE_SERVICE',
                    },
                    {
                        'type': 'METHOD_OF_DELIVERY',
                        'code': 'KS',
                        'name': 'KIOSK',
                    },
                    {
                        'type': 'METHOD_OF_DELIVERY',
                        'code': 'LD',
                        'name': 'LOCAL_DELIVERY',
                    },
                    {
                        'type': 'METHOD_OF_DELIVERY',
                        'code': 'MG',
                        'name': 'MEET_AND_GREET',
                    },
                    {
                        'type': 'METHOD_OF_DELIVERY',
                        'code': 'QR',
                        'name': 'QUICK_RENT',
                    },
                    {
                        'type': 'METHOD_OF_DELIVERY',
                        'code': 'VA',
                        'name': 'VIRTUAL_AISLE',
                    },
                ],
                'closed': False,
                'open_sundays': True,
                'attributes': [
                    'NATIONAL',
                    'ONE_WAYS',
                    'CHOICE',
                    'COUNTER',
                    'EMERALD_AISLE',
                    'EMERALD_RESERVE',
                    'EXECUTIVE_SELECTION',
                    'FBO_DELIVERY',
                    'RESERVE_SERVICE',
                    'KIOSK',
                    'LOCAL_DELIVERY',
                    'MEET_AND_GREET',
                    'QUICK_RENT',
                    'VIRTUAL_AISLE',
                ],
                'default_location_name': location['additional_data']['default_location_name'],
                'physical_location': True,
                'age_options': [
                    {
                        'value': 18,
                        'selected': False,
                        'label': '18',
                    },
                    {
                        'value': 19,
                        'selected': False,
                        'label': '19',
                    },
                    {
                        'value': 20,
                        'selected': False,
                        'label': '20',
                    },
                    {
                        'value': 21,
                        'selected': False,
                        'label': '21',
                    },
                    {
                        'value': 22,
                        'selected': False,
                        'label': '22',
                    },
                    {
                        'value': 23,
                        'selected': False,
                        'label': '23',
                    },
                    {
                        'value': 24,
                        'selected': False,
                        'label': '24',
                    },
                    {
                        'value': 25,
                        'selected': True,
                        'label': '25+',
                    },
                ],
            },
            'alternative_policies': [],
            'after_hours_return': location['after_hours_return'],
            'indicators': [],
            'location_type': 'AIRPORT',
            'paragraphs': [],
            'phones': [
                {
                    'phone_number': '8443709186',
                    'priority': 0,
                    'dialing_code': '1',
                },
            ],
            'station_id': location['station_id'],
            'brand': 'NATIONAL',
            'rental_checklists': [],
            'gps': {
                'latitude': location['gps']['latitude'],
                'longitude': location['gps']['longitude'],
            },
            'booking_urls': [],
            'name': location['name'],
            'methods_of_delivery': [
                'CH',
                'CN',
                'EA',
                'ER',
                'ES',
                'FB',
                'GR',
                'KS',
                'LD',
                'MG',
                'QR',
                'VA',
            ],
            'hours': [],
            'after_hours_pickup': False,
            'after_hour_notice_period': 0,
            'policies': [],
            'available_business_types': [],
            'address': {
                'street_addresses': location['address']['street_addresses'],
                'city': location['address']['city'],
                'country_subdivision_code': location['address']['country_subdivision_code'],
                'country_code': location['address']['country_code'],
                'postal': location['address']['postal'],
            },
            'vehicle_availability_phones': [],
            'offered_car_classes': [],
            'wayfindings': [],
            'type': 'BRANCH',
            'business_types': [
                {
                    'code': 'CDR',
                    'description': 'CRAWFORD_GROUP_DAILY_RENTAL',
                },
                {
                    'code': 'DR',
                    'description': 'DAILY_RENTAL',
                },
                {
                    'code': 'FBO',
                    'description': 'SERVICES_FBO_LOCATION',
                },
                {
                    'code': 'NDR',
                    'description': 'NATIONAL_DAILY_RENTAL',
                },
                {
                    'code': 'NLP',
                    'description': 'NATL_ONEWAY_ANYWHERE_PICKUP',
                },
                {
                    'code': 'NLR',
                    'description': 'NATL_ONEWAY_ANYWHERE_RETURN',
                },
                {
                    'code': 'NRR',
                    'description': 'ACCEPTS_NATRES_RESERVATIONS',
                },
                {
                    'code': 'ORE',
                    'description': 'OVERDUE_RENTAL_EMAIL_CAMPAIGN',
                },
            ],
            'id': location['id'],
            'currency_code': 'USD',
        },
        'requireUnauth': False,
        'renter_age': 25,
        'one_way_rental': False,
        'pickup_time': row['pickup_dt'],
        'ignore_contract_from_profile': False,
        'contract_details': None,
        'return_location_id': location['id'],
        'contract_number': row['contract_number'],
        'pickup_location': {
            'filter_tags': [],
            'airport_code': location['airport_code'],
            'airline_details': [],
            'level_of_service_wayfindings': [],
            'additional_data': {
                'update_timestamp': location['additional_data']['update_timestamp'],
                'java_time_zone': 'America/New_York',
                'formatted_city_state_zip': location['additional_data']['formatted_city_state_zip'],
                'bookable': True,
                'is24HourLocation': location['additional_data']['is24HourLocation'],
                'co_located_station_id': location['station_id'],
                'group_branch_number': location['additional_data']['group_branch_number'],
                'co_located_brand': 'ALAMO',
                'enable_drive_alliance': False,
                'booking_url': 'https://www.nationalcar.com',
                'formatted_phone': location['additional_data']['formatted_phone'],
                'attributes_with_type': [
                    {
                        'type': 'BRAND',
                        'code': '',
                        'name': 'NATIONAL',
                    },
                    {
                        'type': 'BUSINESS_TYPE',
                        'code': '',
                        'name': 'ONE_WAYS',
                    },
                    {
                        'type': 'METHOD_OF_DELIVERY',
                        'code': 'CH',
                        'name': 'CHOICE',
                    },
                    {
                        'type': 'METHOD_OF_DELIVERY',
                        'code': 'CN',
                        'name': 'COUNTER',
                    },
                    {
                        'type': 'METHOD_OF_DELIVERY',
                        'code': 'EA',
                        'name': 'EMERALD_AISLE',
                    },
                    {
                        'type': 'METHOD_OF_DELIVERY',
                        'code': 'ER',
                        'name': 'EMERALD_RESERVE',
                    },
                    {
                        'type': 'METHOD_OF_DELIVERY',
                        'code': 'ES',
                        'name': 'EXECUTIVE_SELECTION',
                    },
                    {
                        'type': 'METHOD_OF_DELIVERY',
                        'code': 'FB',
                        'name': 'FBO_DELIVERY',
                    },
                    {
                        'type': 'METHOD_OF_DELIVERY',
                        'code': 'GR',
                        'name': 'RESERVE_SERVICE',
                    },
                    {
                        'type': 'METHOD_OF_DELIVERY',
                        'code': 'KS',
                        'name': 'KIOSK',
                    },
                    {
                        'type': 'METHOD_OF_DELIVERY',
                        'code': 'LD',
                        'name': 'LOCAL_DELIVERY',
                    },
                    {
                        'type': 'METHOD_OF_DELIVERY',
                        'code': 'MG',
                        'name': 'MEET_AND_GREET',
                    },
                    {
                        'type': 'METHOD_OF_DELIVERY',
                        'code': 'QR',
                        'name': 'QUICK_RENT',
                    },
                    {
                        'type': 'METHOD_OF_DELIVERY',
                        'code': 'VA',
                        'name': 'VIRTUAL_AISLE',
                    },
                ],
                'closed': False,
                'open_sundays': True,
                'attributes': [
                    'NATIONAL',
                    'ONE_WAYS',
                    'CHOICE',
                    'COUNTER',
                    'EMERALD_AISLE',
                    'EMERALD_RESERVE',
                    'EXECUTIVE_SELECTION',
                    'FBO_DELIVERY',
                    'RESERVE_SERVICE',
                    'KIOSK',
                    'LOCAL_DELIVERY',
                    'MEET_AND_GREET',
                    'QUICK_RENT',
                    'VIRTUAL_AISLE',
                ],
                'default_location_name': location['additional_data']['default_location_name'],
                'physical_location': True,
                'age_options': [
                    {
                        'value': 18,
                        'selected': False,
                        'label': '18',
                    },
                    {
                        'value': 19,
                        'selected': False,
                        'label': '19',
                    },
                    {
                        'value': 20,
                        'selected': False,
                        'label': '20',
                    },
                    {
                        'value': 21,
                        'selected': False,
                        'label': '21',
                    },
                    {
                        'value': 22,
                        'selected': False,
                        'label': '22',
                    },
                    {
                        'value': 23,
                        'selected': False,
                        'label': '23',
                    },
                    {
                        'value': 24,
                        'selected': False,
                        'label': '24',
                    },
                    {
                        'value': 25,
                        'selected': True,
                        'label': '25+',
                    },
                ],
            },
            'alternative_policies': [],
            'after_hours_return': location['after_hours_return'],
            'indicators': [],
            'location_type': 'AIRPORT',
            'paragraphs': [],
            'phones': [
                {
                    'phone_number': '8443709186',
                    'priority': 0,
                    'dialing_code': '1',
                },
            ],
            'station_id': location['station_id'],
            'brand': 'NATIONAL',
            'rental_checklists': [],
            'gps': {
                'latitude': location['gps']['latitude'],
                'longitude': location['gps']['longitude'],
            },
            'booking_urls': [],
            'name': location['name'],
            'methods_of_delivery': [
                'CH',
                'CN',
                'EA',
                'ER',
                'ES',
                'FB',
                'GR',
                'KS',
                'LD',
                'MG',
                'QR',
                'VA',
            ],
            'hours': [],
            'after_hours_pickup': False,
            'after_hour_notice_period': 0,
            'policies': [],
            'available_business_types': [],
            'address': {
                'street_addresses': location['address']['street_addresses'],
                'city': location['address']['city'],
                'country_subdivision_code': location['address']['country_subdivision_code'],
                'country_code': location['address']['country_code'],
                'postal': location['address']['postal'],
            },
            'vehicle_availability_phones': [],
            'offered_car_classes': [],
            'wayfindings': [],
            'type': 'BRANCH',
            'business_types': [
                {
                    'code': 'CDR',
                    'description': 'CRAWFORD_GROUP_DAILY_RENTAL',
                },
                {
                    'code': 'DR',
                    'description': 'DAILY_RENTAL',
                },
                {
                    'code': 'FBO',
                    'description': 'SERVICES_FBO_LOCATION',
                },
                {
                    'code': 'NDR',
                    'description': 'NATIONAL_DAILY_RENTAL',
                },
                {
                    'code': 'NLP',
                    'description': 'NATL_ONEWAY_ANYWHERE_PICKUP',
                },
                {
                    'code': 'NLR',
                    'description': 'NATL_ONEWAY_ANYWHERE_RETURN',
                },
                {
                    'code': 'NRR',
                    'description': 'ACCEPTS_NATRES_RESERVATIONS',
                },
                {
                    'code': 'ORE',
                    'description': 'OVERDUE_RENTAL_EMAIL_CAMPAIGN',
                },
            ],
            'id': location['id'],
            'currency_code': 'USD',
        },
        'return_time': row['dropoff_dt'],
        'show_product_code': False,
        'car_class_code': None,
        'show_redemption_rate_to_client': True,
    }

    params = {
        'clean': 'false',
    }

    response = s.post('https://prd-west.webapi.nationalcar.com/gma-national/reservations/initiate', headers=headers, json=json_data)
    response2 = s.get('https://prd-west.webapi.nationalcar.com/gma-national/session/current', headers=headers, params=params)

    return response2.json()